import test from "node:test";import assert from "node:assert/strict";import {LegacyReader,type LegacyReadProvider} from "../src/legacy.js";
const repo="fixture/project", A="a".repeat(40);
const original={
 ".stateowl/router.json":{b64:"eyJzY2hlbWEiOiJzdGF0ZW93bC5yb3V0ZXIvdjEiLCJyb3V0ZXMiOnsid29yayI6eyJwYXRoIjoic3RhdGUvd29yay5qc29uIiwic2VsZWN0IjpbImlkIiwic3RhdHVzIiwibWlzc2luZyJdfX19Cg==",blob:"10e3a6be49cae5803edb31089ac45de09e231a4b"},
 "state/work.json":{b64:"eyJpZCI6IndvcmsiLCJzdGF0dXMiOiJ3b3JraW5nIiwibm9pc2UiOiJvbWl0IiwibGlua3MiOnsiZGV0YWlsIjp7InBhdGgiOiJzdGF0ZS9kZXRhaWwudHh0IiwiZm9ybWF0IjoidGV4dCJ9fX0K",blob:"5e4fe3a82800398c436c08056b606d6e53089d32"},
 "state/detail.txt":{b64:"ZGV0YWlsCg==",blob:"6e63b2f9bf70549cb37deaddd7d19ad5d7340d53"}
};
function provider(overrides:Record<string,{b64:string,blob:string}>={},heads=[A]){let hi=0;const calls:{heads:string[],files:string[]}={heads:[],files:[]};const p:LegacyReadProvider={async resolve(){const h=heads[Math.min(hi++,heads.length-1)]!;calls.heads.push(h);return h},async file(_r,_c,path){calls.files.push(path);const f={...original,...overrides}[path as keyof typeof original];if(!f)throw new Error("NOT_FOUND");return {bytes:Buffer.from(f.b64,"base64"),blob:f.blob}}};return {p,calls};}
const baseExpected={route:"work",head:{repository:repo,ref:"refs/heads/main",commit:A},value:{id:"work",status:"working"},sources:{router:{repository:repo,commit:A,path:".stateowl/router.json",blob:original[".stateowl/router.json"].blob},record:{repository:repo,commit:A,path:"state/work.json",blob:original["state/work.json"].blob}}};

test("legacy projection golden",async()=>{const {p,calls}=provider();assert.deepEqual(await new LegacyReader(p).read({repository:repo,route:"work"}),baseExpected);assert.deepEqual(calls.files,[".stateowl/router.json","state/work.json"])});
test("legacy explicit detail golden",async()=>{const {p}=provider();const got:any=await new LegacyReader(p).read({repository:repo,route:"work",expand:["detail"]});assert.deepEqual(got,{...baseExpected,expanded:{detail:{value:"detail\n",source:{repository:repo,commit:A,path:"state/detail.txt",blob:original["state/detail.txt"].blob}}}})});
test("legacy fresh each call golden",async()=>{const {p,calls}=provider({},[A,A]);const r=new LegacyReader(p);assert.deepEqual(await r.read({repository:repo,route:"work"}),baseExpected);assert.deepEqual(await r.read({repository:repo,route:"work"}),baseExpected);assert.equal(calls.heads.length,2);assert.deepEqual(calls.files,[".stateowl/router.json","state/work.json",".stateowl/router.json","state/work.json"])});
test("legacy expected head mismatch golden",async()=>{const {p,calls}=provider();await assert.rejects(new LegacyReader(p).read({repository:repo,route:"work",expected_head:"b".repeat(40)}),/EXPECTED_HEAD_MISMATCH/);assert.deepEqual(calls.files,[])});
test("legacy duplicate router key golden",async()=>{const {p,calls}=provider({".stateowl/router.json":{b64:"eyJzY2hlbWEiOiJzdGF0ZW93bC5yb3V0ZXIvdjEiLCJzY2hlbWEiOiJ4Iiwicm91dGVzIjp7fX0=",blob:"27e8c90cd6e18e673f5f9c2cd81fc1e916abf1a3"}});await assert.rejects(new LegacyReader(p).read({repository:repo,route:"work"}),/JSON_DUPLICATE_KEY/);assert.deepEqual(calls.files,[".stateowl/router.json"])});
test("legacy cross repository requires commit golden",async()=>{const {p,calls}=provider({"state/work.json":{b64:"eyJpZCI6IndvcmsiLCJzdGF0dXMiOiJ3b3JraW5nIiwibm9pc2UiOiJvbWl0IiwibGlua3MiOnsiZGV0YWlsIjp7InJlcG9zaXRvcnkiOiJmaXh0dXJlL290aGVyIiwicGF0aCI6ImRldGFpbC50eHQiLCJmb3JtYXQiOiJ0ZXh0In19fQ==",blob:"fbc6411c86770af17c55a1a1040b01dc67121053"}});await assert.rejects(new LegacyReader(p).read({repository:repo,route:"work",expand:["detail"]}),/LINK_COMMIT_REQUIRED/);assert.deepEqual(calls.files,[".stateowl/router.json","state/work.json"])});
